
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE1_SOC(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

mult16_tester m16_t (.CLOCK_50(CLOCK_50),.KEY(KEY),.HEX5(HEX5), .HEX4(HEX4),.HEX3(HEX3),.HEX2(HEX2),.HEX1(HEX1), .HEX0(HEX0));


//=======================================================
//  Structural coding
//=======================================================



endmodule
